services:
  - type: web
    name: communityos-backend
    runtime: docker
    rootDir: Community-os-backend
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: COOKIE_SECURE
        value: "true"
      - key: SEED_DB
        value: "false"
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        sync: false
      - key: REFRESH_SECRET
        sync: false
      - key: REFRESH_EXPIRES_IN
        sync: false
      - key: BCRYPT_SALT_ROUNDS
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: APP_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_SUBJECT
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: PAYMONGO_SECRET_KEY
        sync: false
      - key: PAYMONGO_PUBLIC_KEY
        sync: false
      - key: PAYMONGO_WEBHOOK_SECRET
        sync: false