import { PERMISSIONS } from '@/constants/permissions'

export interface RoleTemplate {
  key: string
  label: string
  description: string
  permissionCodes: string[]
}

export const ROLE_TEMPLATES: RoleTemplate[] = [
  {
    key: 'treasurer',
    label: 'Treasurer',
    description: 'Finance office-holder: assessments, payments, billing, reports',
    permissionCodes: [
      PERMISSIONS.dashboardView,
      PERMISSIONS.assessmentView,
      PERMISSIONS.assessmentCreate,
      PERMISSIONS.assessmentUpdate,
      PERMISSIONS.assessmentDelete,
      PERMISSIONS.assessmentIssue,
      PERMISSIONS.assessmentCancel,
      PERMISSIONS.paymentView,
      PERMISSIONS.paymentCreate,
      PERMISSIONS.paymentUpdate,
      PERMISSIONS.paymentDelete,
      PERMISSIONS.paymentCancel,
      PERMISSIONS.financeViewOwn,
      PERMISSIONS.financeViewAll,
      PERMISSIONS.financeVerify,
      PERMISSIONS.financeReject,
      PERMISSIONS.financeRefund,
      PERMISSIONS.financeCancel,
      PERMISSIONS.financeManage,
      PERMISSIONS.financeWaive,
      PERMISSIONS.financeImport,
      PERMISSIONS.financeExport,
      PERMISSIONS.billingView,
      PERMISSIONS.reportsExport,
      PERMISSIONS.notificationView,
      PERMISSIONS.notificationUpdate,
    ],
  },
  {
    key: 'secretary',
    label: 'Secretary',
    description: 'Communication office-holder: announcements, events, polls, documents',
    permissionCodes: [
      PERMISSIONS.dashboardView,
      PERMISSIONS.announcementCreate,
      PERMISSIONS.announcementView,
      PERMISSIONS.announcementUpdate,
      PERMISSIONS.announcementDelete,
      PERMISSIONS.announcementPublish,
      PERMISSIONS.eventCreate,
      PERMISSIONS.eventView,
      PERMISSIONS.eventUpdate,
      PERMISSIONS.eventDelete,
      PERMISSIONS.eventPublish,
      PERMISSIONS.eventCancel,
      PERMISSIONS.eventComplete,
      PERMISSIONS.pollCreate,
      PERMISSIONS.pollView,
      PERMISSIONS.pollUpdate,
      PERMISSIONS.pollDelete,
      PERMISSIONS.pollPublish,
      PERMISSIONS.pollClose,
      PERMISSIONS.documentCreate,
      PERMISSIONS.documentView,
      PERMISSIONS.documentUpdate,
      PERMISSIONS.documentDelete,
      PERMISSIONS.documentPublish,
      PERMISSIONS.documentArchive,
      PERMISSIONS.notificationView,
      PERMISSIONS.notificationUpdate,
      PERMISSIONS.settingsView,
    ],
  },
  {
    key: 'operations',
    label: 'Operations',
    description: 'Operations office-holder: facilities, reservations, visitors',
    permissionCodes: [
      PERMISSIONS.dashboardView,
      PERMISSIONS.facilityCreate,
      PERMISSIONS.facilityView,
      PERMISSIONS.facilityUpdate,
      PERMISSIONS.facilityDelete,
      PERMISSIONS.reservationView,
      PERMISSIONS.reservationCreate,
      PERMISSIONS.reservationUpdate,
      PERMISSIONS.reservationDelete,
      PERMISSIONS.reservationApprove,
      PERMISSIONS.reservationReject,
      PERMISSIONS.reservationCancel,
      PERMISSIONS.reservationComplete,
      PERMISSIONS.visitorCreate,
      PERMISSIONS.visitorView,
      PERMISSIONS.visitorUpdate,
      PERMISSIONS.visitorDelete,
      PERMISSIONS.visitorCheckIn,
      PERMISSIONS.visitorCheckOut,
      PERMISSIONS.visitorCancel,
      PERMISSIONS.notificationView,
      PERMISSIONS.notificationUpdate,
      PERMISSIONS.settingsView,
    ],
  },
  {
    key: 'guard',
    label: 'Guard',
    description: 'Gate security: visitor check-in/out + facility viewing',
    permissionCodes: [
      PERMISSIONS.dashboardView,
      PERMISSIONS.visitorView,
      PERMISSIONS.visitorCreate,
      PERMISSIONS.visitorCheckIn,
      PERMISSIONS.visitorCheckOut,
      PERMISSIONS.visitorCancel,
      PERMISSIONS.facilityView,
    ],
  },
]
