export const PERMISSIONS = {
  dashboardView: 'dashboard.view',

  userCreate: 'user.create',
  userView: 'user.view',
  userUpdate: 'user.update',
  userDelete: 'user.delete',

  roleManage: 'role.manage',
  permissionView: 'permission.view',
  permissionManage: 'permission.manage',

  residentCreate: 'resident.create',
  residentView: 'resident.view',
  residentUpdate: 'resident.update',
  residentDelete: 'resident.delete',
  residentVerify: 'resident.verify',
  residentImport: 'resident.import',
  residentExport: 'resident.export',

  householdCreate: 'household.create',
  householdView: 'household.view',
  householdUpdate: 'household.update',
  householdDelete: 'household.delete',
  householdImport: 'household.import',
  householdExport: 'household.export',

  vehicleCreate: 'vehicle.create',
  vehicleView: 'vehicle.view',
  vehicleUpdate: 'vehicle.update',
  vehicleDelete: 'vehicle.delete',
  vehicleVerify: 'vehicle.verify',
  vehicleImport: 'vehicle.import',
  vehicleExport: 'vehicle.export',

  stickerCreate: 'sticker.create',
  stickerView: 'sticker.view',
  stickerUpdate: 'sticker.update',
  stickerDelete: 'sticker.delete',
  stickerVerify: 'sticker.verify',

  petCreate: 'pet.create',
  petView: 'pet.view',
  petUpdate: 'pet.update',
  petDelete: 'pet.delete',
  petVerify: 'pet.verify',
  petImport: 'pet.import',
  petExport: 'pet.export',

  visitorCreate: 'visitor.create',
  visitorView: 'visitor.view',
  visitorUpdate: 'visitor.update',
  visitorDelete: 'visitor.delete',
  visitorCheckIn: 'visitor.check-in',
  visitorCheckOut: 'visitor.check-out',
  visitorCancel: 'visitor.cancel',

  staffCreate: 'staff.create',
  staffView: 'staff.view',
  staffUpdate: 'staff.update',
  staffDelete: 'staff.delete',
  staffImport: 'staff.import',
  staffExport: 'staff.export',

  maintenanceCreate: 'maintenance.create',
  maintenanceView: 'maintenance.view',
  maintenanceUpdate: 'maintenance.update',
  maintenanceDelete: 'maintenance.delete',
  maintenanceAssign: 'maintenance.assign',
  maintenanceStart: 'maintenance.start',
  maintenanceResolve: 'maintenance.resolve',
  maintenanceCancel: 'maintenance.cancel',

  announcementCreate: 'announcement.create',
  announcementView: 'announcement.view',
  announcementUpdate: 'announcement.update',
  announcementDelete: 'announcement.delete',
  announcementPublish: 'announcement.publish',

  eventCreate: 'event.create',
  eventView: 'event.view',
  eventUpdate: 'event.update',
  eventDelete: 'event.delete',
  eventPublish: 'event.publish',
  eventCancel: 'event.cancel',
  eventComplete: 'event.complete',

  pollCreate: 'poll.create',
  pollView: 'poll.view',
  pollUpdate: 'poll.update',
  pollDelete: 'poll.delete',
  pollPublish: 'poll.publish',
  pollClose: 'poll.close',
  pollVote: 'poll.vote',

  complaintCreate: 'complaint.create',
  complaintView: 'complaint.view',
  complaintUpdate: 'complaint.update',
  complaintDelete: 'complaint.delete',
  complaintAssign: 'complaint.assign',
  complaintResolve: 'complaint.resolve',
  complaintClose: 'complaint.close',

  notificationView: 'notification.view',
  notificationUpdate: 'notification.update',

  facilityView: 'facility.view',
  facilityCreate: 'facility.create',
  facilityUpdate: 'facility.update',
  facilityDelete: 'facility.delete',

  reservationView: 'reservation.view',
  reservationCreate: 'reservation.create',
  reservationUpdate: 'reservation.update',
  reservationDelete: 'reservation.delete',
  reservationApprove: 'reservation.approve',
  reservationReject: 'reservation.reject',
  reservationCancel: 'reservation.cancel',
  reservationComplete: 'reservation.complete',

  documentCreate: 'document.create',
  documentView: 'document.view',
  documentUpdate: 'document.update',
  documentDelete: 'document.delete',
  documentPublish: 'document.publish',
  documentArchive: 'document.archive',
  uploadFile: 'upload.file',

  billingView: 'billing.view',
  billingManage: 'billing.manage',

  assessmentView: 'assessment.view',
  assessmentCreate: 'assessment.create',
  assessmentUpdate: 'assessment.update',
  assessmentDelete: 'assessment.delete',
  assessmentIssue: 'assessment.issue',
  assessmentCancel: 'assessment.cancel',

  paymentView: 'payment.view',
  paymentCreate: 'payment.create',
  paymentUpdate: 'payment.update',
  paymentDelete: 'payment.delete',
  paymentCancel: 'payment.cancel',

  financeViewOwn: 'finance.view_own',
  financeViewAll: 'finance.view_all',
  financeVerify: 'finance.verify',
  financeReject: 'finance.reject',
  financeRefund: 'finance.refund',
  financeCancel: 'finance.cancel',
  financeImport: 'finance.import',
  financeExport: 'finance.export',
  financeManage: 'finance.manage',
  financeWaive: 'finance.waive',

  financeExpenseView: 'finance.expense_view',
  financeExpenseCreate: 'finance.expense_create',
  financeExpenseUpdate: 'finance.expense_update',
  financeExpenseDelete: 'finance.expense_delete',
  financeExpenseImport: 'finance.expense_import',
  financeExpenseExport: 'finance.expense_export',
  financeIncomeStatementView: 'finance.income_statement_view',

  subscriptionView: 'subscription.view',
  subscriptionManage: 'subscription.manage',
  invoiceView: 'invoice.view',
  invoiceManage: 'invoice.manage',

  reportsExport: 'reports.export',
  analyticsView: 'analytics.view',
  auditView: 'audit.view',
  auditManage: 'audit.manage',

  settingsView: 'settings.view',
  settingsManage: 'settings.manage',

  communityBranding: 'community.branding',
} as const

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
